enum GoalType {
  EGGS_LAID = 1;
  UNKNOWN_GOAL = 100;
}

enum RewardType {
  CASH = 1;
  GOLD = 2;
  SOUL_EGGS = 3;
  EGGS_OF_PROPHECY = 4;
  EPIC_RESEARCH_ITEM = 5;
  PIGGY_FILL = 6;
  PIGGY_MULTIPLIER = 7;
  PIGGY_LEVEL_BUMP = 8;
  BOOST = 9;
  BOOST_TOKEN = 10;
  ARTIFACT = 11;
  ARTIFACT_CASE = 12;
  CHICKEN = 13;
  SHELL_SCRIPT = 14;
  VIRTUE_GEM = 15;
  UNKNOWN_REWARD = 100;
}

enum Egg {
  EDIBLE = 1;
  SUPERFOOD = 2;
  MEDICAL = 3;
  ROCKET_FUEL = 4;
  SUPER_MATERIAL = 5;
  FUSION = 6;
  QUANTUM = 7;
  IMMORTALITY = 8;
  TACHYON = 9;
  GRAVITON = 10;
  DILITHIUM = 11;
  PRODIGY = 12;
  TERRAFORM = 13;
  ANTIMATTER = 14;
  DARK_MATTER = 15;
  AI = 16;
  NEBULA = 17;
  UNIVERSE = 18;
  ENLIGHTENMENT = 19;
  CURIOSITY = 50;
  INTEGRITY = 51;
  HUMILITY = 52;
  RESILIENCE = 53;
  KINDNESS = 54;
  CHOCOLATE = 100;
  EASTER = 101;
  WATERBALLOON = 102;
  FIREWORK = 103;
  PUMPKIN = 104;
  CUSTOM_EGG = 200;
  UNKNOWN = 1000;
}

message GameModifier {
  optional GameDimension dimension = 1;
  enum GameDimension {
    INVALID = 0;
    EARNINGS = 1;
    AWAY_EARNINGS = 2;
    INTERNAL_HATCHERY_RATE = 3;
    EGG_LAYING_RATE = 4;
    SHIPPING_CAPACITY = 5;
    HAB_CAPACITY = 6;
    VEHICLE_COST = 7;
    HAB_COST = 8;
    RESEARCH_COST = 9;
  }

  optional double value = 2;
  optional string description = 3;
}

message Contract {
  optional string identifier = 1;
  optional string name = 9;
  optional string description = 10;
  optional Egg egg = 2;
  optional string custom_egg_id = 25;

  repeated Goal goals = 3;
  message Goal {
    optional GoalType type = 1;
    optional double target_amount = 2;
    optional RewardType reward_type = 3;
    optional string reward_sub_type = 4;
    optional double reward_amount = 5;
    optional double target_soul_eggs = 6;
  }

  repeated GoalSet goal_sets = 16;
  message GoalSet {
    repeated Goal goals = 1;
  }

  repeated GradeSpec grade_specs = 20;
  message GradeSpec {
    optional PlayerGrade grade = 1;
    repeated Goal goals = 2;
    repeated GameModifier modifiers = 3;
    optional double length_seconds = 4;
  }

  optional string season_id = 23;
  optional bool coop_allowed = 4;
  optional uint32 max_coop_size = 5;
  optional uint32 max_boosts = 12;
  optional double minutes_per_token = 15 [default = 60];
  optional double chicken_run_cooldown_minutes = 18 [default = 180];
  optional double start_time = 17;
  optional double expiration_time = 6;
  optional double length_seconds = 7;
  optional double max_soul_eggs = 13;
  optional uint32 min_client_version = 14;
  optional bool leggacy = 19;
  optional bool cc_only = 22;
  repeated string default_shell_ids = 24;
  optional bool debug = 11;
  optional string key = 21;

  enum PlayerGrade {
    GRADE_UNSET = 0;
    GRADE_C = 1;
    GRADE_B = 2;
    GRADE_A = 3;
    GRADE_AA = 4;
    GRADE_AAA = 5;
  }
}
