#!/usr/bin/env bash

export PATH="./node_modules/.bin:$PATH"
help() { declare -F | awk -v ORS="   " '{ print $3 }'; echo; }

_playwright_version() {
  jq -r '.devDependencies["@playwright/test"]' package.json | sed -e 's/\^/v/'
}

playwright:local() {
  exec docker run \
    --interactive --tty --rm --ipc=host --net=host \
    --volume .:/app:rw --env BASE_URL="$BASE_URL" \
    --env ASTRO_TELEMETRY_DISABLED=1 \
    "mcr.microsoft.com/playwright:$(_playwright_version)" \
    bash -c "cd /app; yarn playwright test $*"
}

# works on my machine™  —dukeceph
# on mac or windows maybe need other variables/volumes
# ref https://www.oddbird.net/2022/11/30/headed-playwright-in-docker/
playwright:ui() {
  xhost +local:docker
  exec docker run \
    --interactive --tty --rm --ipc=host --net=host\
    --env DISPLAY="$DISPLAY" \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
    --volume .:/app:rw --env BASE_URL="$BASE_URL" \
    --env ASTRO_TELEMETRY_DISABLED=1 \
    "mcr.microsoft.com/playwright:$(_playwright_version)" \
    /bin/bash -c "cd /app; yarn playwright test --ui $*"
}

lint:fix() {
  prettier --write . | grep --color=always -v unchanged
  eslint --fix --format=pretty src
}

parse-contract-proto() {
  local txt
  txt=$(echo "$1" | base64 -d | protoc --decode Contract contract.proto)
  jq -n \
    --arg kevid "$(echo "$txt" | grep '^identifier:' | cut -d'"' -f2)" \
    --arg customEgg "$(echo "$txt" | grep '^custom_egg_id:' | cut -d'"' -f2)" \
    '{($kevid): $customEgg}'
}

refresh-colleggtibles() {
  printf 'export default ' > src/lib/colleggtible_contracts.ts
  curl -sSL "https://raw.githubusercontent.com/carpetsage/egg/refs/heads/main/periodicals/data/colleggtible-contracts.json" \
    | jq --raw-output '.[].proto' \
    | xargs -n1 ./Taskfile parse-contract-proto \
    | jq --slurp 'reduce .[] as $item ({}; . * $item)' \
    >> src/lib/colleggtible_contracts.ts
}

# as a general style guide, any package.json task that doesn't
# fit in a hundred (ish) characters so should probably move to
# a function here for improved readability and maintainability
# ------------------------------------------------------------
# this splits argv into words and processes them as a command:
# $ ./Taskfile _playwright_version
# simply runs the `_playwright_version` function defined above
#
# i use a shell alias, `run=./Taskfile`, that you may like too
"$@"
